secret_tailscale_authkey: ENC[AES256_GCM,data:OXDHWwsKwI8LpqNDn92xR2/IlhYlZ7I1QWrzM+husnjR3hIwu3wthrT5RVo8zBXQZ9qLLdMteluAIhxalA==,iv:g2en8LN4sBn2u7qVD+9bLFLuDiGmwApXR9WQO2afpCw=,tag:rvUI3ClVlxGnjOEoEvlkfQ==,type:str]
secret_th_tofu_password: ENC[AES256_GCM,data:cd7JJRb+QJNb/7qniQ6JC1RqMFyrSAWPBg==,iv:wKzpEzpUZD8skLlHF7eKMo1C+oe4sg901DPbCpBwULU=,tag:GtnHZWfPmCeP5loTU9gfRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljjjk3gge0dz5le5uj4nxdv9qrp4gucwrtsd598604rnzja60ytqdpl4cp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwekV5dzhVckI3aEF5RFNY
            RmU5dXYrKzk3VHUwWWFVNWoybTUwUEg0TmtZCkZDYTdRdWJOazVBQkw1Ykg5ZDVI
            UHd4M3VVd1psdlJsckRkMFFFM2RGNzQKLS0tIGtFZzEyODVFdGVJSjZkNlZMalVv
            T2xvSDNabDVyS1hKUGpuNitFcjVLRDgKrTnrPtwOHct/5feJeYqMSV75fyAJsA3+
            k0jrnq3Wy0vDYLp/nxM5MvPtSvRnAPxrwJ7u5vDqVKKIUKNhvoiitQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T15:26:24Z"
    mac: ENC[AES256_GCM,data:fDUMNDvu0/tiB+0dk9vpciqRVGa3BrMlc5nud6/CqOJ1wHpmuKoY2V5wiSuGzfqBqTgop6KSEci36ngsFuak6TA0D/FQdaR4F2A3X7kzLHBKrdWOqmnSBH3NJh5JoXGaHwCaQc1u9p0Z8k8+UKzO6iQFMNMcP3hC7Yy3DeF/4kw=,iv:YAUvvsIM5oC6ajPyhE9HZbEEoQoK/itSTRhBHXXZdtQ=,tag:WFXjIWhtTYhPw/CnXPE/Cg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
