name: Mirror and run GitLab CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/spacehlship/dotlab"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "NayanTheSpaceGuy"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "58826574"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
